
RUN_STATISTIC_ANALYSIS = False
#Markers Filtering:
FRACTION_FAILED_COL_NAME = 'Missing Data Fraction per Marker'
FRACTION_HETEROZYGOUS_COL_NAME = 'Heterozygous Reads Fraction per Marker'
MARKER_FRACTION_FAILED_FILTER = 0.199
MARKER_FRACTION_HETEROZYGOUS_FILTER = 1
DELETE_BAD_MARKERS_BASED_ON_PART1=True

#Samples Filtering:
SAMPLES_SUCCESS_MARKERS_COL_NAME = "Fraction of markers successfully genotyped"
SAMPLES_HETEROZYGOUS_COL_NAME = "Fraction of heterozygous genotypes"
SAMPLES_FRACTION_SUCCESS_MARKERS_FILTER = 0.85
SAMPLES_FRACTION_HETEROZYGOUS_FILTER = 0.35
